### ISSUE TITLE
Write a make file. 

### ISSUE THREAD

**Issue by andrewhowdencom** [djmattyg007/hr#1]
This is a stub - I fully intend to write the make file. However, this issue is created so it goes on the list of issues I need to keep track of. 

default: 
     @echo usage

build:
     # Build all the things

install: build
     # copy to /usr/local/bin/ 

clean: 
     # delete all the builds

**Comment by djmattyg007** [comment]
This project now uses autotools to generate the `Makefile` necessary for building and compiling the software.
